[package]
name = "memfile_test"
version = "0.1.0"
edition = "2021"

[dependencies]
bincode = "1.3.3"
fixedstr = "0.2.8"
mmap-fixed = "0.1.5"
serde = { version = "1.0.150", features = ["derive"] }
serde-big-array = "0.4.1"
shared_memory = "0.12.4"

